### PR TITLE
Added a connection for Intrepid's hardware interfaces

### PR DESCRIPTION
**Pull request by syntroniks**
There are several items to identify in this PR. See inline comments for notes.
This PR is to address issue #12

### CODE REVIEW

**Comment by syntroniks** [comment]
I ended up writing some sort of a deframer so that bytes reported back to higher levels don't include ISO-TP control bytes.
There has got to be a better way to do this in python. PR update coming soon.

**Comment by syntroniks** [comment]
Roger that,

With respect to the Iso15765 support, it seems that the library has different support for RX and TX. Under TX, you can give a message and it gets 'framed'. If a message requires multiple transmissions, the hardware interface accepts, decodes, and should respect the flow control response from a remote node.
In RX, it seems as if single transmission messages are passed through unmodified. For multiple transmission messages (in receive), the interface generates and sends a flow control packet.

As an example, the python-ics driver would have something similar to this:
*TX*
`transmit(b'\x3E\x00')`
`bytes transmitted: b'\x02\x3E\x00'` as expected
*RX*
`rx_bytes = receive()`
`bytes received (rx_bytes): b'\x02\x7E\x00'`

As for the serial number, Yes, perhaps more flexible instantiation is in the mix.
I'll parameterize those parameters you called out as well.

**Comment by syntroniks** [comment]
This PR might be abandoned if python-can is a suitable alternative and can be integrated. I'm interested to see what @christiansandberg comes up with.

**Comment by pylessard** [comment]
Me too, but in any case, I will come up with a solution for python-can before end of 2018. I've written somthing functional this weekend. I'll give it some unit test love and release something in about 2 weeks.

**Comment by pylessard** [comment]
I am closing this pull request as release v1.7 supports python-can and @syntroniks said that we should abandon it in that case.

I believe it could still be nice to supports Intrepid IsoTP .dll in the future, but I can't do it as I don't have their hardware and they are quite costy for personal uses.

Feel free to reopen if you would like to support it.

**Pull request closed without merging**
